fixBug PropertyNotFoundException
During deploy on clean Wildfly 19 installation there were the foollowing exception:
org.hibernate.PropertyNotFoundException: Could not locate setter method for property [org.apache.roller.weblogger.pojos.WeblogEntryComment#emptyString]
Adding missing <transient> element for emptyString property in orm descriptor fixes the problem.