Set struts.convention.action.includeJars=false.
Caused a NoClassDefFoundError in struts when it tried to inspect a log4j2 class via reflection which had optional dependencies.